/*
 * notifier
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SendNotificationBody {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "subject")]
    pub subject: String,
}

impl SendNotificationBody {
    pub fn new(message: String, user_id: String, subject: String) -> SendNotificationBody {
        SendNotificationBody {
            message,
            user_id,
            subject,
        }
    }
}


