/* tslint:disable */
/* eslint-disable */
/**
 * notifier
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTelegramChannelBody
 */
export interface AddTelegramChannelBody {
    /**
     * 
     * @type {string}
     * @memberof AddTelegramChannelBody
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AddTelegramChannelBody
     */
    telegramUsername: string;
}

/**
 * Check if a given object implements the AddTelegramChannelBody interface.
 */
export function instanceOfAddTelegramChannelBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "telegramUsername" in value;

    return isInstance;
}

export function AddTelegramChannelBodyFromJSON(json: any): AddTelegramChannelBody {
    return AddTelegramChannelBodyFromJSONTyped(json, false);
}

export function AddTelegramChannelBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTelegramChannelBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'telegramUsername': json['telegram_username'],
    };
}

export function AddTelegramChannelBodyToJSON(value?: AddTelegramChannelBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
        'telegram_username': value.telegramUsername,
    };
}

