/* tslint:disable */
/* eslint-disable */
/**
 * notifier
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendNotificationBody
 */
export interface SendNotificationBody {
    /**
     * 
     * @type {string}
     * @memberof SendNotificationBody
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof SendNotificationBody
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof SendNotificationBody
     */
    userId: string;
}

/**
 * Check if a given object implements the SendNotificationBody interface.
 */
export function instanceOfSendNotificationBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "subject" in value;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function SendNotificationBodyFromJSON(json: any): SendNotificationBody {
    return SendNotificationBodyFromJSONTyped(json, false);
}

export function SendNotificationBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendNotificationBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'message': json['message'],
        'userId': json['user_id'],
    };
}

export function SendNotificationBodyToJSON(value?: SendNotificationBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject': value.subject,
        'message': value.message,
        'user_id': value.userId,
    };
}

